/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Historico;

import Class.Clientes;
import Class.HistoricoDeCompras;
import Class.Jogos;
import Class.Joins;
import Dados.BDClientes;
import Dados.BDHistorico;
import Dados.BDJogos;
import Dados.BDJoins;
import Utilidade.TableModelGames;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fifol
 */
public class AlterarHistorico extends javax.swing.JFrame {
    TelaPrincipal telaprinc;
    CadastrarHistorico cadastroHis;
    

    ArrayList<HistoricoDeCompras> listaHistorico = new ArrayList<HistoricoDeCompras>();
    ArrayList<Joins> historicoJoin = new ArrayList<Joins>();
    ArrayList<Clientes> listaCliente = new ArrayList<Clientes>();
    ArrayList<Jogos> listaJogos = new ArrayList<Jogos>();
    
    /**
     * Creates new form Alterar
     */
    public AlterarHistorico() {
        initComponents();
        this.telaprinc = new TelaPrincipal();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboAlterCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboAlterJogo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alterData = new datechooser.beans.DateChooserCombo();
        comboAlterQnt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboAlterPag = new javax.swing.JComboBox<>();
        alterTime = new com.github.lgooddatepicker.components.TimePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Cliente");

        comboAlterCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAlterCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlterClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Game");

        comboAlterJogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Data");

        jLabel5.setText("Quantidade");

        alterData.setCalendarPreferredSize(new java.awt.Dimension(370, 250));

        comboAlterQnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Hora");

        jLabel6.setText("Pagamento");

        comboAlterPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Atualizar");

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboAlterCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboAlterJogo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(alterData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(comboAlterPag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(comboAlterQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(alterTime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAlterCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlterJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(alterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboAlterQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboAlterPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int index;
        index = Integer.valueOf(this.telaprinc.index);
        
        TableModelGames tablemodelgame = new TableModelGames();
        
        carregaCombos();
        
        
        if (telaprinc.Tabela.getSelectedRow() != -1) {
            
            try {
                cadastroHis.
            } catch (Exception e) {
            }
            
            
            
            
            
            for(int i = index; i <= index; i++){
                
                HistoricoDeCompras historico = new HistoricoDeCompras();
                
                DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
                String dataFormatada = dtOutput.format(historicoJoin.get(i).getData());
                alterData.setText(dataFormatada);
                
                comboAlterCliente.setSelectedItem(tablemodelgame.get(i).getNomeCliente());
                
                DateFormat hrOutput = new SimpleDateFormat("HH:mm");
//                String horaFormatada = hrOutput.format(historicoJoin.get(i).getHora());
                historico.setHora(listaHistorico.get(index - 1).getHora());
                
                
                
            }
                
                
//                    try {
//                        TelefoneDAO TDAO = new TelefoneDAO();
//                        TDAO.atualizar(tel);                    
//                        carregaFones();
//                    } catch (ErpDAOException ex) {
//                        System.out.println("problema");
//                    }
                
            }
        
    }//GEN-LAST:event_formWindowOpened

    private void comboAlterClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlterClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAlterClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarHistorico().setVisible(true);
            }
        });
    }
    
    public void carregaCombos(){
        
        //START COMBOS
        //Carregar combo Clientes
        try {
            comboAlterCliente.removeAllItems();
            BDClientes BDC = new BDClientes();
            listaCliente = BDC.listar();
        } catch (Exception ex) {
            System.out.println("Erro qualquer" + ex);
        }

        for (int i = 0; i < listaCliente.size(); i++) {
            comboAlterCliente.addItem(listaCliente.get(i).getNomeCliente());
        }  
        
        //Carregar combo Games
        try {
            comboAlterJogo.removeAllItems();
            BDJogos BDJ = new BDJogos();
            listaJogos = BDJ.listar();
        } catch (Exception ex) {
            System.out.println("Erro qualquer" + ex);
        }

        for (int i = 0; i < listaJogos.size(); i++) {
            comboAlterJogo.addItem(listaJogos.get(i).getNomeJogo());
        }
        
        //Carregar combo Qquantidade
        try {
            comboAlterQnt.removeAllItems();
        } catch (Exception ex) {
            System.out.println("Erro qualquer" + ex);
        }

        for (int i = 1; i < 11; i++) {
            comboAlterQnt.addItem(""+i);
        }
        
        
        //Carregar combo Pagamentos
        try {
            comboAlterPag.removeAllItems();
            BDHistorico BDH = new BDHistorico();
            listaHistorico = BDH.listarPagamentos();
            
            
            
        } catch (Exception ex) {
            System.out.println("Erro qualquer" + ex);
        }
        
        
        for (int i = 0; i < listaHistorico.size(); i++) {
            comboAlterPag.addItem(listaHistorico.get(i).getTipoPagamento());
        }  
        //END COMBOS//
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo alterData;
    private com.github.lgooddatepicker.components.TimePicker alterTime;
    private javax.swing.JComboBox<String> comboAlterCliente;
    private javax.swing.JComboBox<String> comboAlterJogo;
    private javax.swing.JComboBox<String> comboAlterPag;
    private javax.swing.JComboBox<String> comboAlterQnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
